version: '3.3'

services:

  nginx:
    build:
      context: nginx
    container_name: proxy
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/node
    tty: true
    ports:
      - "3000:3000"
    command:
      - node index.js
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: 
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

volumes:
  db_data:

networks:
  node-network:
    driver: bridge